### ISSUE TITLE
Cannot add the task to my build

### ISSUE THREAD

**Issue by snavarropino** [jessehouwing/vsts-ensure-tests#4]
Hi, I a not able to add this task to my pipeline. 

I created an agentless phase, set up the dependency with my agent phase that performs build and test, but I  can not add the taks, it is only listed on marketplace. Please look at following image:

![ensure](https://user-images.githubusercontent.com/11868679/47899979-9f508c80-de7b-11e8-8f4d-47071601e462.png)

**Comment by gregpakes** [comment]
This happened to me too.  Make sure you refresh the page and ensure the Agentless Job is selected.  It then worked for me.
